name: Keep Alive

on:
  schedule:
    - cron: '*/7 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Render App
        run: |
          curl -s -o /dev/null -w "%{http_code}\n" https://no-reply-accounts-verify.onrender.com/
